# Generated by Django 3.0.7 on 2020-06-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherboard', models.CharField(choices=[('Asus Prime', 'Asus Prime'), ('Gigabyte', 'Gigabyte'), ('ASRock Fatal', 'ASRock Fatal')], max_length=100)),
                ('supp_processors', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD'), ('Intel e AMD', 'Intel e AMD')], max_length=100)),
                ('r_slots', models.PositiveIntegerField(choices=[(2, '2'), (4, '4')])),
                ('m_ram', models.PositiveIntegerField(choices=[(16, '16'), (64, '64')])),
                ('has_integrated_video', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(choices=[('Intel Core i5', 'Intel Core i5'), ('Intel Core i7', 'Intel Core i7'), ('AMD Athlon', 'AMD Athlon'), ('AMD Ryzen 7', 'AMD Ryzen 7')], max_length=100)),
                ('processor_brand', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RamMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_memory', models.CharField(choices=[('Hiper X', 'Hiper X')], max_length=100)),
                ('ram_memory_size', models.PositiveIntegerField(choices=[(4, '4'), (8, '8'), (16, '16'), (32, '32'), (64, '64')])),
            ],
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_card', models.CharField(choices=[('Gigabyte Geforce GTX 1060 6GB', 'Gigabyte Geforce GTX 1060 6GB'), ('PNY RTX 2060 6GB', 'PNY RTX 2060 6GB'), ('Radeon RX 580 8GB', 'Radeon RX 580 8GB')], max_length=100)),
            ],
        ),
    ]
