# Generated by Django 3.0.7 on 2020-06-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200625_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_card', models.CharField(choices=[('Gigabyte Geforce GTX 1060 6GB', 'Gigabyte Geforce GTX 1060 6GB'), ('PNY RTX 2060 6GB', 'PNY RTX 2060 6GB'), ('Radeon RX 580 8GB', 'Radeon RX 580 8GB')], max_length=100)),
            ],
        ),
    ]
