# Generated by Django 3.0.7 on 2020-06-26 00:21

from django.db import migrations

# Generated by Django 3.0.7 on 2020-06-25 23:54

from django.db import migrations

def populate_videocards(apps, schema_editor):

    VideoCard = apps.get_model('app', 'videocard')
    [
        VideoCard(video_card="Gigabyte Geforce GTX 1060 6GB").save(),
        VideoCard(video_card="PNY RTX 2060 6GB").save(),
        VideoCard(video_card="Radeon RX 580 8GB").save()
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_videocard'),
    ]

    operations = [
        migrations.RunPython(populate_videocards)
    ]
