# Generated by Django 3.0.7 on 2020-06-26 02:37

from django.db import migrations


def populate_motherboards(apps, schema_editor):

    Motherboard = apps.get_model('app', 'motherboard')
    [
        Motherboard(motherboard="Asus Prime", supp_processors="Intel", r_slots=2, m_ram=16, has_integrated_video=False).save(),
        Motherboard(motherboard="Gigabyte", supp_processors="AMD", r_slots=2, m_ram=16, has_integrated_video=False).save(),
        Motherboard(motherboard="ASRock Fatal", supp_processors="Intel e AMD", r_slots=4, m_ram=64, has_integrated_video=True).save(),
    ]

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_4'),
    ]

    operations = [
        migrations.RunPython(populate_motherboards)
    ]