# Generated by Django 3.0.7 on 2020-06-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200626_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_memory', models.CharField(choices=[('Hiper X', 'Hiper X')], max_length=100)),
                ('ram_memory_size', models.PositiveIntegerField(choices=[(4, '4'), (8, '8'), (16, '16'), (32, '32'), (64, '64')])),
            ],
        ),
    ]
